install.packages(c('devtools', 'shiny', 'shinythemes', 'shinyBS', 'shinyjs', 'europepmc', 'DT', 'data.table', 'markdown', 'rclipboard', 'shinycssloaders', 'shinydashboard', 'shinyFiles', 'shinyFeedback','shinyHeatmaply', 'shinyjqui', 'shinyWidgets', 'bsplus', 'colourpicker'), repos="https://mirrors.nics.utk.edu/cran")
#install.packages('shiny')
#install.packages('shinythemes')
#install.packages('shinyBS')
#install.packages('shinyjs')
#install.packages('europepmc')
#install.packages('DT')
#install.pakcages('data.table')
#install.packages('markdown')
#install.packages('rclipboard')
#install_github('shinycssloaders')
#install.packages("shinydashboard")
#install.packages('shinyFiles')
#install.packages("shinyFeeedback")
#install.packages('shinyHeatmaply')
#install.packages('shinyjqui')
#install.packages("shinyWidgets")
#install.packages("bsplus")
#install.packages("colourpicker")

library(devtools)
install_github("cstubben/euPMC")
install_github("robear22890/shinyLP", "/home/rgilmore/R/x86_64-pc-linux-gnu-library/3.3")
install_github("mkuhn/dict")
install_github('ayayron/shinydnd')
install_github("Appsilon/shiny.semantic")
install_github("rstudio/miniUI")
install_github('zachcp/msaR')

source("https://bioconductor.org/biocLite.R")
biocLite("ggtree")
biocLite("cummeRbund")
